In [5]:
import pandas as pd
import re

In [5]:
file = "../cleaned/cleaned_fighters.csv"
df = pd.read_csv(file)
df.head()
duplicates = list(df[df['fighter_name'].duplicated()]['fighter_name'])
duplicates

['Mike Davis',
 'Joey Gomez',
 'Tony Johnson',
 'Michael McDonald',
 'Bruno Silva',
 'Jean Silva',
 'Victor Valenzuela']

In [6]:
id = df[df['fighter_name'] == 'Beneil Dariush'].index
print(f'id is : {id}')

id is : Index([872], dtype='int64')

In [9]:
df = pd.read_csv("../cleaned/fighter_fights.csv")
df.head()

   fight_id  fighter_id
0         1         873
1         1        2714
2         2        4328
3         2        3746
4         3        2231

In [13]:
features = ['Dave Menne', 'Fabiano Iha', '0', '0', '37 of 99', '8 of 22', '37%', '36%', '130 of 199', '44 of 61', '0 of 0', '1 of 12', '---', '8%', '1', '0', '0', '0', '9:45', '0:38', 'Dave Menne', 'Fabiano Iha', 
'0', '0', '16 of 42', '6 of 11', '38%', '54%', '28 of 55', '13 of 18', '0 of 0', '1 of 6', '---', '16%', '1', '0', '0', '0', '2:47', '0:36', 'Dave Menne', 'Fabiano Iha', '0', '0', '10 of 26', '1 of 7', 
'38%', '14%', '57 of 79', '18 of 25', '0 of 0', '0 of 1', '---', '0%', '0', '0', '0', '0', '4:09', '0:00', 'Dave Menne', 'Fabiano Iha', '0', '0', '11 of 31', '1 of 4', '35%', '25%', '45 of 65', '13 of 18', 
'0 of 0', '0 of 5', '---', '0%', '0', '0', '0', '0', '2:49', '0:02', 'Dave Menne', 'Fabiano Iha', '37 of 99', '8 of 22', '37%', '36%', '26 of 85', '4 of 16', '8 of 10', '2 of 4', '3 of 4', '2 of 2', '8 of 46', 
'2 of 12', '17 of 30', '6 of 10', '12 of 23', '0 of 0', 'Dave Menne', 'Fabiano Iha', '16 of 42', '6 of 11', '38%', '54%', '10 of 35', '4 of 9', '4 of 5', '1 of 1', '2 of 2', '1 of 1', '2 of 15', '1 of 2', 
'12 of 23', '5 of 9', '2 of 4', '0 of 0', 'Dave Menne', 'Fabiano Iha', '10 of 26', '1 of 7', '38%', '14%', '6 of 21', '0 of 5', '3 of 3', '0 of 1', '1 of 2', '1 of 1', '4 of 14', '1 of 7', '2 of 3', '0 of 0', 
'4 of 9', '0 of 0', 'Dave Menne', 'Fabiano Iha', '11 of 31', '1 of 4', '35%', '25%', '10 of 29', '0 of 2', '1 of 2', '1 of 2', '0 of 0', '0 of 0', '2 of 17', '0 of 3', '3 of 4', '1 of 1', '6 of 10', '0 of 0']


#fighter_id, round, kd, sig.str, total.str, td, sub.att, rev, ctrl, head, body, leg, distance, clinch, ground
print(len(features))
if len(features) != 0:
    rounds = (len(features) - 38) // 38 
totals = features[:20]
fighter_a = totals[0:20:2]
fighter_a
fighter_b = totals[1:20:2]
fighter_b

152

['Fabiano Iha',
 '0',
 '8 of 22',
 '36%',
 '44 of 61',
 '1 of 12',
 '8%',
 '0',
 '0',
 '0:38']

In [79]:
features = ['Dave Menne', 'Fabiano Iha', '0', '0', '37 of 99', '8 of 22', '37%', '36%', '130 of 199', '44 of 61', '0 of 0', '1 of 12', '---', '8%', '1', '0', '0', '0', '9:45', '0:38', 'Dave Menne', 'Fabiano Iha', 
'0', '0', '16 of 42', '6 of 11', '38%', '54%', '28 of 55', '13 of 18', '0 of 0', '1 of 6', '---', '16%', '1', '0', '0', '0', '2:47', '0:36', 'Dave Menne', 'Fabiano Iha', '0', '0', '10 of 26', '1 of 7', 
'38%', '14%', '57 of 79', '18 of 25', '0 of 0', '0 of 1', '---', '0%', '0', '0', '0', '0', '4:09', '0:00', 'Dave Menne', 'Fabiano Iha', '0', '0', '11 of 31', '1 of 4', '35%', '25%', '45 of 65', '13 of 18', 
'0 of 0', '0 of 5', '---', '0%', '0', '0', '0', '0', '2:49', '0:02', 'Dave Menne', 'Fabiano Iha', '37 of 99', '8 of 22', '37%', '36%', '26 of 85', '4 of 16', '8 of 10', '2 of 4', '3 of 4', '2 of 2', '8 of 46', 
'2 of 12', '17 of 30', '6 of 10', '12 of 23', '0 of 0', 'Dave Menne', 'Fabiano Iha', '16 of 42', '6 of 11', '38%', '54%', '10 of 35', '4 of 9', '4 of 5', '1 of 1', '2 of 2', '1 of 1', '2 of 15', '1 of 2', 
'12 of 23', '5 of 9', '2 of 4', '0 of 0', 'Dave Menne', 'Fabiano Iha', '10 of 26', '1 of 7', '38%', '14%', '6 of 21', '0 of 5', '3 of 3', '0 of 1', '1 of 2', '1 of 1', '4 of 14', '1 of 7', '2 of 3', '0 of 0', 
'4 of 9', '0 of 0', 'Dave Menne', 'Fabiano Iha', '11 of 31', '1 of 4', '35%', '25%', '10 of 29', '0 of 2', '1 of 2', '1 of 2', '0 of 0', '0 of 0', '2 of 17', '0 of 3', '3 of 4', '1 of 1', '6 of 10', '0 of 0']

features = []
# print(len(features))
# if len(features) != 0:
#     rounds = (len(features) - 38) // 38

# round = 0
# kd_idx = 22 + round * 20
# sig_str_idx = 24 + round * 20
# total_str_idx = 28 + round * 20
# td_idx = 30 + round * 20
# sub_att_idx = 34 + round * 20
# rev_idx = 36 + round * 20
# ctr_time_idx = 38 * round * 20
# head_idx = (44 + rounds * 20) + round * 18
# body_idx = (46 + rounds * 20) + round * 18
# leg_idx = (48 + rounds * 20) + round * 18
# distance_idx = (50 + rounds * 20) + round * 18
# clinch_idx = (52 + rounds * 20) + round * 18
# ground_idx = (54 + rounds * 20) + round * 18
# features[head_idx]

fighter_id, round, kd, sig.str, total.str, td, sub.att, rev, ctrl, head, body, leg, distance, clinch, ground

In [80]:
def rows_from_fight(features, fight_id, fighter_a_id, fighter_b_id):
    rows = []
    rounds = 0
    if len(features) != 0:
        rounds = (len(features) - 38) // 38

    for round in range(rounds):
        kd_idx = 22 + round * 20
        sig_str_idx = 24 + (round*20)
        total_str_idx = 28 + round * 20
        td_idx = 30 + round * 20
        sub_att_idx = 34 + round * 20
        rev_idx = 36 + round * 20
        ctr_time_idx = 38 + round * 20
        head_idx = (44 + rounds * 20) + round * 18
        body_idx = (46 + rounds * 20) + round * 18
        body_idx = (46 + rounds * 20) + round * 18
        leg_idx = (48 + rounds * 20) + round * 18
        distance_idx = (50 + rounds * 20) + round * 18
        clinch_idx = (52 + rounds * 20) + round * 18
        ground_idx = (54 + rounds * 20) + round * 18
        rows.append({
            "fight_id": fight_id,
            "fighter_id": fighter_a_id,
            "round": round+1,
            "kd": features[kd_idx],
            "sig_str": features[sig_str_idx],
            "total_str": features[total_str_idx],
            "td": features[td_idx],
            "sub_att": features[sub_att_idx],
            "reversals": features[rev_idx],
            "ctr_time": features[ctr_time_idx],
            "head": features[head_idx],
            "body": features[body_idx],
            "leg": features[leg_idx],
            "distance": features[distance_idx],
            "clinch": features[clinch_idx],
            "ground": features[ground_idx]
            })
        
    for round in range(rounds):
        kd_idx = 23 + round * 20
        sig_str_idx = 25 + (round*20)
        total_str_idx = 29 + round * 20
        td_idx = 31 + round * 20
        sub_att_idx = 35 + round * 20
        rev_idx = 37 + round * 20
        ctr_time_idx = 39 + round + 20
        head_idx = (45 + rounds * 20) + round * 18
        body_idx = (47 + rounds * 20) + round * 18
        leg_idx = (49 + rounds * 20) + round * 18
        distance_idx = (51 + rounds * 20) + round * 18
        clinch_idx = (53 + rounds * 20) + round * 18
        ground_idx = (55 + rounds * 20) + round * 18
        rows.append({
            "fight_id": fight_id,
            "fighter_id": fighter_b_id,
            "round": round+1,
            "kd": features[kd_idx],
            "sig_str": features[sig_str_idx],
            "total_str": features[total_str_idx],
            "td": features[td_idx],
            "sub_att": features[sub_att_idx],
            "reversals": features[rev_idx],
            "ctr_time": features[ctr_time_idx],
            "head": features[head_idx],
            "body": features[body_idx],
            "leg": features[leg_idx],
            "distance": features[distance_idx],
            "clinch": features[clinch_idx],
            "ground": features[ground_idx]
            })
    return rows

In [81]:
rows = rows_from_fight(features, 100, 1, 2)
rows

[]

In [4]:
data = pd.read_csv("rounds.csv")
data.head()

,fight_id,fighter_id,round,kd,sig_str,total_str,td,sub_att,reversals,ctr_time,head,body,leg,distance,clinch,ground
0,1,2715,1,0,1 of 1,2 of 2,1 of 1,1,0,--,1 of 1,0 of 0,0 of 0,0 of 0,1 of 1,0 of 0
1,1,874,1,0,0 of 4,1 of 5,0 of 0,0,0,--,0 of 2,0 of 0,0 of 2,0 of 3,0 of 1,0 of 0
2,2,3747,1,0,1 of 1,1 of 1,0 of 1,1,0,--,0 of 0,1 of 1,0 of 0,0 of 0,1 of 1,0 of 0
3,2,4329,1,0,1 of 1,2 of 2,0 of 0,0,0,--,0 of 0,0 of 0,1 of 1,1 of 1,0 of 0,0 of 0
4,3,3292,1,0,11 of 17,74 of 86,1 of 1,0,0,--,9 of 15,1 of 1,1 of 1,1 of 1,1 of 1,9 of 15

In [ ]:
def clean_rounds(rounds_csv):
    data = pd.read_csv(rounds_csv)
    cols = ["sig_str", "total_str", "td", "head", "body", "leg", "distance", "clinch", "ground"]
    
    for col in cols:
        extracted = data[col].str.extract(r'(\d+)\s+of\s+(\d+)').astype(int)
        data[f"{col}_landed"] = extracted[0]
        data[f"{col}_attempted"] = extracted[1]
    
    return data

In [ ]:
new_df = clean_rounds(data)
new_df.head()